# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/d/IRP-SOC-main/Design/ET1035_SRC/MEMORY/RAM/block_mem_1/block_mem_1.xci
# IP: The module: 'block_mem_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/d/IRP-SOC-main/ET1035_PJT_sim/ET1035_pjt.gen/sources_1/ip/block_mem_1/block_mem_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_mem_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/d/IRP-SOC-main/Design/ET1035_SRC/MEMORY/RAM/block_mem_1/block_mem_1.xci
# IP: The module: 'block_mem_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/d/IRP-SOC-main/ET1035_PJT_sim/ET1035_pjt.gen/sources_1/ip/block_mem_1/block_mem_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_mem_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
